In [1]:
# change int to float, float ot int 

a=9.4
b=int(a)

In [2]:
b


9

In [3]:
c=float(b)

In [4]:
c

9.0

In [5]:
d=complex(b,a)
d

(9+9.4j)

In [6]:
int(True)

1

In [7]:
int(False)

0

In [8]:
#dictionaries

In [9]:
keys=[1,2]
values=['a','b']

In [10]:
d=dict(zip(keys,values))
d

{1: 'a', 2: 'b'}

In [11]:
d[3]='c'
d

{1: 'a', 2: 'b', 3: 'c'}

In [12]:
del d[2]
d


{1: 'a', 3: 'c'}

In [13]:
d.get(1)

'a'

In [14]:
d.get(2)

In [15]:
d.get(1,'not found')

'a'

In [16]:
d.get(2,'not found')

'not found'

In [17]:
#sets

s={23,45,23,675,5}

In [18]:
s

{5, 23, 45, 675}

In [19]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [20]:
type(list(range(0,10)))

list

In [21]:
type((range(0,10)))

range

In [22]:
#assigning

a,b=5,6
a

5

In [23]:
-a

-5

In [24]:
a

5

In [25]:
a=-a
a

-5

In [26]:
# number conversions - binary,octal,hexa octal


In [27]:
bin(25)

'0b11001'

In [28]:
oct(25)

'0o31'

In [29]:
hex(25)

'0x19'

In [30]:
hex(10)

'0xa'

In [31]:
0xf

15

In [32]:
0b1101

13

In [33]:
# swap two variables

In [34]:
a=5
b=6
a=b
b=a   #wrong
a,b

(6, 6)

In [35]:
a=5
b=6
temp=a
a=b
b=temp
a,b

(6, 5)

In [36]:
a,b=5,6
a=a+b
b=a-b
a=a-b
a,b

(6, 5)

In [37]:
XOR

NameError: name 'XOR' is not defined

In [ ]:
a,b=5,6
a,b=b,a  # beauty of python 
a,b

In [ ]:
a,b=5,6
a=a^b
b=a^b
a,b

In [ ]:
~12

In [ ]:

# mathematical operators

In [ ]:
import math


In [ ]:
math.sqrt(25)

In [ ]:
math.ceil(2.3)

In [ ]:
import math as j

In [ ]:
j.sqrt(25)

In [ ]:
math.sqrt(25)

In [ ]:
j.pow(3,2)  #3**2

In [ ]:
# input func

In [ ]:
x=input('enter a charac ')[0]
x

In [ ]:
result = eval(input('enter an expression: '))
result

In [ ]:
# loops

In [ ]:
print('telusko ',end='')    # to print in same line 
print('rocks ')

In [ ]:
print('telusko ')
print('rocks ')

In [ ]:
for i in range(10,2):
    print(i) 

In [ ]:
list(range(20,10,-1 ))

In [ ]:
# printing patterns

In [ ]:
for i in range(4):
    for j in range(4):
        print('#',end='')
    print( )

In [ ]:
for i in range(4):
    for j in range(i):
        print('#',end='')
    print( )

In [ ]:
for i in range(4):
    for j in range(4-i):
        print('#',end='')
    print( )

In [ ]:
# arrays,pip,numpy


In [ ]:
from array import *

arr=array('i',[1,2,3])
arr
print(arr)

In [ ]:
arr=array('I',[1,2,3])
arr

In [ ]:
arr.buffer_info()

In [ ]:
arr.count(4)

In [ ]:
arr.index(3)

In [ ]:
arr.pop(2)
arr

In [ ]:
arr.insert(1,7)
arr


In [ ]:
arr.insert(3,5)
arr

In [ ]:
arr.typecode

In [ ]:
newarr=array(arr.typecode,(a*2 for a in arr))
newarr

In [ ]:
from array import *
arr=array('i',[])
n=int(input('length of array: '))
i=0
while i<n:
    a=input('please enter the next arr dgigit: ')
    if a.isdigit()==True:
        arr.append(int(a))
        i+=1
    else:
        print('please enter only digits')
print(arr)

In [ ]:
k=int(input('enter a value from array : '))
i=0
for e in arr:
    if e==k:
        print('value found at index position:',i)  
        break
    i+=1
else:
     print('not founf')
    
    

In [ ]:
k=int(input('enter a value from array : '))
i=0
for i in range(len(arr)):
    if arr[i]==k:
        print('value found at index position:',i) 
        #break
else:
    print('nf')

    

In [ ]:
print(arr.index(k))

In [ ]:
arr=array('i',[1,2],[8,9])

In [ ]:
from array import *
from numpy import *

In [ ]:
arr=array([1,2,3],[4,5,6])
arr

In [ ]:
arr1= array ([1,2,b],int)
print(arr1)
(arr1.dtype)


In [ ]:
arr=linspace(0,10,1)    # b-a/n-1 both a,b included
print(arr)

arr1=linspace(0,10,4)    # b-a/n-1 both a,b included
print(arr1)

In [ ]:
arr=arange(1,11,2)    # like range b not included
print(arr)

In [ ]:
arr=logspace(1,3,4)   #log of 10**1,10**4
print(arr)



In [ ]:
arr=zeros(5)
print(arr)

In [ ]:
arr=ones(7,int)
print(arr)

In [ ]:
#mathematical ops on arrays 


In [ ]:
from numpy import *
arr=array([1,2,3])
arr=arr+5
print(arr)

In [ ]:
arr1=array([2,3,4])
arr2=arr**arr1
print(arr2)

In [ ]:
sin(arr)

In [ ]:
log(arr)

In [ ]:
min(arr)

In [ ]:
sqrt(arr)

In [ ]:
sum(arr)

In [ ]:
sort(arr)

In [ ]:
concatenate([arr,arr1])

In [ ]:
#copying arrays

In [48]:
from array import *
from numpy import *
arr=array([1,2,3])
arr1=arr.copy()
arr[2]=9
print(id(arr))
print(id(arr1))
arr1

140654503452496
140654558927856


array([1, 2, 3])

In [49]:
# matrices


In [53]:
arr=array([
            [1,2,3],
            [4,5,6]
    
        ])
m=matrix(arr)
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [54]:
m.flatten()

matrix([[1, 2, 3, 4, 5, 6]])

In [55]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [56]:
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [57]:
m.reshape(3,2)

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [58]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [59]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr1=array([1,2,3,4,5,6,7,8,9,10,11,12])

In [67]:
m=arr1.reshape(6,2)
m


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [68]:
m.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
m

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [71]:
m*m

array([[  1,   4],
       [  9,  16],
       [ 25,  36],
       [ 49,  64],
       [ 81, 100],
       [121, 144]])

In [72]:
m=array([1,2,3,4,5,6,7,8])

In [77]:
m=m.reshape(2,4)

In [78]:
print(m)

[[1 2 3 4]
 [5 6 7 8]]


In [79]:
m+5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [80]:
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
#fibonacii series

In [94]:
def fib(n):
    
    if n==1:
        print('fib=[0]')
    
    fib=[0,1]
    if n>1:
        for i in range(2,n):
            x=fib[i-1]+fib[i-2]
            fib.append(x)
        print(fib)

In [96]:
fib(1)

fib=[0]


In [97]:
# factorial 

In [109]:
def fact(n):
    
    if n==0:
        print('0!=1')
    
    else:
        temp=1
        for i in list(range(1,n+1)):
            temp=temp*i
        print(temp)
    

In [113]:
fact(0)

0!=1


In [1]:
# __name__, main

In [3]:
print(__name__)

__main__


In [51]:
with open('myfile.txt','w') as t:
    t.write('Hi \nhello \nsimmi')

In [52]:
with open('myfile.txt','r') as t:
    print(t.read())

Hi 
hello 
simmi


In [53]:
with open('myfile.txt','r') as t:
    print(t.readline(),end='')
    print(t.readline())
    print(t.readline())
    

Hi 
hello 

simmi


In [73]:
f1=open('abc.txt','w')

In [74]:
f1.write('hi \n hello')

10

In [75]:
print(f1.read())

UnsupportedOperation: not readable

In [67]:
with open('abc.txt','w') as f:
    f.write('Hi \nhello ')

In [68]:
with open('abc.txt','r') as f:
    print(f.read())

Hi 
hello 
